// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tryktqmmjylhzmuibcmi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRyeWt0cW1tanlsaHptdWliY21pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQyNzU5ODQsImV4cCI6MjA0OTg1MTk4NH0.RT9WpERltMiozDpOQqujE4L7PuRMbqabWdyVaKxv0cQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);